/**
 *
 * @author heske.timjonathan
 */
package gruppeneinteilung.gui;

import gruppeneinteilung.helper.PrintPDF;
import gruppeneinteilung.helper.Speicherung;
import gruppeneinteilung.model.Gruppeneinteilung;
import gruppeneinteilung.model.Klasse;
import gruppeneinteilung.model.Jahrgang;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.GridLayout;
import java.io.File;
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.SpinnerNumberModel;

public class GUI extends javax.swing.JFrame {

    private Gruppeneinteilung ge;
    private Jahrgang aktuellerJahrgang;
    private File file;

    /**
     * Creates new form GUI
     */
    public GUI() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *///
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxJahrgang = new javax.swing.JComboBox();
        jSpinnerAnzahlKlassen = new javax.swing.JSpinner(new SpinnerNumberModel(4,1,10,1));
        jLabelKlassen = new javax.swing.JLabel();
        jComboBoxSortierung = new javax.swing.JComboBox<String>();
        jButtonJahrgangDrucken = new javax.swing.JButton();
        jLabelSchülergesamt = new javax.swing.JLabel();
        jLabelKatholisch = new javax.swing.JLabel();
        jLabelEthik = new javax.swing.JLabel();
        jLabelEvangelisch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelMännlich = new javax.swing.JLabel();
        jLabelWeiblich = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxReligion = new javax.swing.JCheckBox();
        jCheckBoxZweig = new javax.swing.JCheckBox();
        jCheckBoxFremdsprache = new javax.swing.JCheckBox();
        jButtonEinstellungReligion = new javax.swing.JButton();
        jButtonEinstellungZweig = new javax.swing.JButton();
        jButtonEinstellungFremdsprache = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelKlassen = new javax.swing.JPanel();
        jPanelSport = new javax.swing.JPanel();
        jPanelReligion = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemImport = new javax.swing.JMenuItem();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jMenuItemSettings = new javax.swing.JMenuItem();
        jMenuItemPrint = new javax.swing.JMenuItem();
        jMenuItemClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kursmanager");
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jComboBoxJahrgang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jahrgang wählen", "5", "6", "7", "8", "9", "10"}));
        jComboBoxJahrgang.setEnabled(false);
        jComboBoxJahrgang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJahrgangActionPerformed(evt);
            }
        });

        jSpinnerAnzahlKlassen.setEnabled(false);
        jSpinnerAnzahlKlassen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerAnzahlKlassenStateChanged(evt);
            }
        });

        jLabelKlassen.setText("Anzahl Klassen:");
        jLabelKlassen.setEnabled(false);

        jComboBoxSortierung.setEnabled(false);
        jComboBoxSortierung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sortierung wählen", "Alphabetisch", "Männlich/Weiblich", "Religion", "Zweig" }));
        jComboBoxSortierung.setName(""); // NOI18N
        jComboBoxSortierung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSortierungActionPerformed(evt);
            }
        });

        jButtonJahrgangDrucken.setText("Jahrgang drucken");
        jButtonJahrgangDrucken.setEnabled(false);
        jButtonJahrgangDrucken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJahrgangDruckenActionPerformed(evt);
            }
        });

        jLabelSchülergesamt.setText("Anzahl Schüler gesamt:");
        jLabelSchülergesamt.setVisible(false);

        jLabelKatholisch.setText("Anzahl Katholisch:");
        jLabelKatholisch.setVisible(false);

        jLabelEthik.setText("Anzahl Ethik:");
        jLabelEthik.setVisible(false);

        jLabelEvangelisch.setText("Anzahl Evangelisch:");
        jLabelEvangelisch.setVisible(false);

        jLabel1.setText("");
        jLabel1.setVisible(false);

        jLabelMännlich.setText("Anzahl Männlich:");
        jLabelMännlich.setVisible(false);

        jLabelWeiblich.setText("Anzahl Weiblich:");
        jLabelWeiblich.setVisible(false);

        jLabel2.setText("");
        jLabel2.setVisible(false);

        jLabel3.setText("");
        jLabel3.setVisible(false);

        jCheckBoxReligion.setText("Religion");
        jCheckBoxReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxReligionActionPerformed(evt);
            }
        });
        jCheckBoxReligion.setEnabled(false);

        jCheckBoxZweig.setText("Zweig");
        jCheckBoxZweig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxZweigActionPerformed(evt);
            }
        });
        jCheckBoxZweig.setEnabled(false);

        jCheckBoxFremdsprache.setText("Fremdsprache");
        jCheckBoxFremdsprache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFremdspracheActionPerformed(evt);
            }
        });
        jCheckBoxFremdsprache.setEnabled(false);

        jButtonEinstellungReligion.setText("Einstellung");
        jButtonEinstellungReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEinstellungReligionActionPerformed(evt);
            }
        });
        jButtonEinstellungReligion.setEnabled(false);

        jButtonEinstellungZweig.setText("Einstellung");
        jButtonEinstellungZweig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEinstellungZweigActionPerformed(evt);
            }
        });
        jButtonEinstellungZweig.setEnabled(false);

        jButtonEinstellungFremdsprache.setText("Einstellung");
        jButtonEinstellungFremdsprache.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEinstellungFremdspracheActionPerformed(evt);
            }
        });
        jButtonEinstellungFremdsprache.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSchülergesamt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxSortierung, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxJahrgang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonJahrgangDrucken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelKlassen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerAnzahlKlassen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelKatholisch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEthik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEvangelisch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMännlich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelWeiblich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxReligion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jButtonEinstellungReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxZweig)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEinstellungZweig, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxFremdsprache)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEinstellungFremdsprache, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxJahrgang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelKlassen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerAnzahlKlassen))
                .addGap(18, 18, 18)
                .addComponent(jComboBoxSortierung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonJahrgangDrucken)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxReligion)
                    .addComponent(jButtonEinstellungReligion))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxZweig)
                    .addComponent(jButtonEinstellungZweig))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxFremdsprache)
                    .addComponent(jButtonEinstellungFremdsprache))
                .addGap(18, 18, 18)
                .addComponent(jLabelSchülergesamt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelKatholisch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEthik, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEvangelisch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMännlich, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWeiblich, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
        );

        jComboBoxSortierung.getAccessibleContext().setAccessibleName("");

        jPanelKlassen.setLayout(new java.awt.GridLayout(1, 8));
        jTabbedPane1.addTab("Allgemein", jPanelKlassen);

        jPanelSport.setLayout(new java.awt.GridLayout(1, 8));
        jTabbedPane1.addTab("Sportgruppen", jPanelSport);

        jPanelReligion.setLayout(new java.awt.GridLayout(1, 8));
        jTabbedPane1.addTab("Religionsgruppen", jPanelReligion);

        jMenu1.setText("File");

        jMenuItemImport.setText("Import");
        jMenuItemImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemImport);

        jMenuItemOpen.setText("Open");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOpen);

        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenuItemSave.setEnabled(false);
        jMenu1.add(jMenuItemSave);

        jMenuItemSaveAs.setText("Save As");
        jMenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveAsActionPerformed(evt);
            }
        });
        jMenuItemSaveAs.setEnabled(false);
        jMenu1.add(jMenuItemSaveAs);

        jMenuItemSettings.setText("Settings");
        jMenuItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSettingsActionPerformed(evt);
            }
        });
        jMenuItemSettings.setEnabled(false);
        jMenu1.add(jMenuItemSettings);

        jMenuItemPrint.setText("Print");
        jMenuItemPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrintActionPerformed(evt);
            }
        });
        jMenuItemPrint.setEnabled(false);
        jMenu1.add(jMenuItemPrint);

        jMenuItemClose.setText("Close");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxJahrgangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJahrgangActionPerformed
        // TODO add your handling code here:
        evalueteJahrgangsAuswahl();
    }//GEN-LAST:event_jComboBoxJahrgangActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        Speicherung sp = new Speicherung();
        ge = sp.serialisierungLaden();
        this.setTitle("Kursmanager - " + ge.getFile().toString());
        evalueteJahrgangsAuswahl();
        jMenuItemSave.setEnabled(true);
        jMenuItemSaveAs.setEnabled(true);
        jMenuItemPrint.setEnabled(true);
        jComboBoxJahrgang.setEnabled(true);
        jButtonJahrgangDrucken.setEnabled(true);
        jSpinnerAnzahlKlassen.setEnabled(true);
        jComboBoxSortierung.setEnabled(true);
        jCheckBoxReligion.setEnabled(true);
        jCheckBoxZweig.setEnabled(true);
        jCheckBoxFremdsprache.setEnabled(true);
        jButtonEinstellungReligion.setEnabled(true);
        jButtonEinstellungZweig.setEnabled(true);
        jButtonEinstellungFremdsprache.setEnabled(true);
        jLabelKlassen.setEnabled(true);
        jLabelSchülergesamt.setVisible(true);

        jLabelKatholisch.setVisible(true);

        jLabelEvangelisch.setVisible(true);

        jLabelEthik.setVisible(true);

        jLabelMännlich.setVisible(true);

        jLabelWeiblich.setVisible(true);

        jLabel1.setVisible(true);

        jLabel2.setVisible(true);

        jLabel3.setVisible(true);

    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSettingsActionPerformed

    private void jMenuItemImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportActionPerformed
        // TODO add your handling code here:
        ge = new Gruppeneinteilung();
        ge.asvImport();
        jMenuItemSave.setEnabled(true);
        jMenuItemSaveAs.setEnabled(true);
        jMenuItemPrint.setEnabled(true);
        jComboBoxJahrgang.setEnabled(true);
        jButtonJahrgangDrucken.setEnabled(true);
        jSpinnerAnzahlKlassen.setEnabled(true);
        jComboBoxSortierung.setEnabled(true);
        jCheckBoxReligion.setEnabled(true);
        jCheckBoxZweig.setEnabled(true);
        jCheckBoxFremdsprache.setEnabled(true);
        jButtonEinstellungReligion.setEnabled(true);
        jButtonEinstellungZweig.setEnabled(true);
        jButtonEinstellungFremdsprache.setEnabled(true);
        jLabelKlassen.setEnabled(true);
        jLabelSchülergesamt.setVisible(true);

        jLabelKatholisch.setVisible(true);

        jLabelEvangelisch.setVisible(true);

        jLabelEthik.setVisible(true);

        jLabelMännlich.setVisible(true);

        jLabelWeiblich.setVisible(true);

        jLabel1.setVisible(true);

        jLabel2.setVisible(true);

        jLabel3.setVisible(true);

    }//GEN-LAST:event_jMenuItemImportActionPerformed

    private void jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseActionPerformed
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemCloseActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        // TODO add your handling code here:
        new Speicherung(ge).speichern();
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jComboBoxSortierungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSortierungActionPerformed
        // TODO add your handling code here:
        String sortierung = jComboBoxSortierung.getSelectedItem().toString();
        for (Klasse k : aktuellerJahrgang.getKlassen()) {
            switch (sortierung) {
                case "Alphabetisch":
                    k.sortierenName();
                    break;
                case "Männlich/Weiblich":
                    k.sortierenGeschlecht();
                    break;
                case "Religion":
                    k.sortierenReligion();
                    break;
                case "Zweig":
                    k.sortierenZweig();
                    break;
            }
        }
        Component[] comps = jPanelKlassen.getComponents();
        for (Component comp : comps) {
            GruppenPanel gp = (GruppenPanel) comp;
            gp.aktualisiereListModel();
            gp.revalidate();
            gp.repaint();
        }
        jPanelKlassen.revalidate();
        jPanelKlassen.repaint();
    }//GEN-LAST:event_jComboBoxSortierungActionPerformed

    private void jMenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsActionPerformed
        // TODO add your handling code here:
        new Speicherung(ge).speichernUnter();
        this.setTitle("Kursmanager - " + ge.getFile().toString());
    }//GEN-LAST:event_jMenuItemSaveAsActionPerformed

    private void jMenuItemPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrintActionPerformed
        // TODO add your handling code here:
        PrintPDF printPdf = new PrintPDF(ge);
        printPdf.Drucken("Alle Klassen");
    }//GEN-LAST:event_jMenuItemPrintActionPerformed

    private void jButtonJahrgangDruckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJahrgangDruckenActionPerformed
        // TODO add your handling code here:
        PrintPDF printPdf = new PrintPDF(ge);
        int n = Integer.parseInt(jComboBoxJahrgang.getSelectedItem().toString());
        Jahrgang j = ge.getJahrgang(n);
        String z = Integer.toString(n);
        printPdf.druckeJahrgang(j, "Jahrgang" + z);
    }//GEN-LAST:event_jButtonJahrgangDruckenActionPerformed

    private void jCheckBoxReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxReligionActionPerformed
        // TODO add your handling code here:
        aktuellerJahrgang.setNachReligion();
    }//GEN-LAST:event_jCheckBoxReligionActionPerformed

    private void jButtonEinstellungReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEinstellungReligionActionPerformed
        // TODO add your handling code here:
        new EinstellungFrame().setVisible(true);
    }//GEN-LAST:event_jButtonEinstellungReligionActionPerformed

    private void jCheckBoxZweigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxZweigActionPerformed
        // TODO add your handling code here:
        aktuellerJahrgang.setNachZweig();
    }//GEN-LAST:event_jCheckBoxZweigActionPerformed

    private void jCheckBoxFremdspracheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFremdspracheActionPerformed
        // TODO add your handling code here:
        aktuellerJahrgang.setNachFremdsprache();
    }//GEN-LAST:event_jCheckBoxFremdspracheActionPerformed

    private void jButtonEinstellungZweigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEinstellungZweigActionPerformed
        // TODO add your handling code here:
        new EinstellungFrame().setVisible(true);
    }//GEN-LAST:event_jButtonEinstellungZweigActionPerformed

    private void jButtonEinstellungFremdspracheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEinstellungFremdspracheActionPerformed
        // TODO add your handling code here:
        new EinstellungFrame().setVisible(true);
    }//GEN-LAST:event_jButtonEinstellungFremdspracheActionPerformed

    private void jSpinnerAnzahlKlassenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerAnzahlKlassenStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jSpinnerAnzahlKlassenStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEinstellungFremdsprache;
    private javax.swing.JButton jButtonEinstellungReligion;
    private javax.swing.JButton jButtonEinstellungZweig;
    private javax.swing.JButton jButtonJahrgangDrucken;
    private javax.swing.JCheckBox jCheckBoxFremdsprache;
    private javax.swing.JCheckBox jCheckBoxReligion;
    private javax.swing.JCheckBox jCheckBoxZweig;
    private javax.swing.JComboBox jComboBoxJahrgang;
    private javax.swing.JComboBox<String> jComboBoxSortierung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEthik;
    private javax.swing.JLabel jLabelEvangelisch;
    private javax.swing.JLabel jLabelKatholisch;
    private javax.swing.JLabel jLabelKlassen;
    private javax.swing.JLabel jLabelMännlich;
    private javax.swing.JLabel jLabelSchülergesamt;
    private javax.swing.JLabel jLabelWeiblich;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemImport;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemPrint;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JMenuItem jMenuItemSettings;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelKlassen;
    private javax.swing.JPanel jPanelReligion;
    private javax.swing.JPanel jPanelSport;
    private javax.swing.JSpinner jSpinnerAnzahlKlassen;
    private javax.swing.SpinnerModel modelKlassenAnzahl = new javax.swing.SpinnerNumberModel(0, 0, 10, 1);
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    public void evalueteJahrgangsAuswahl() {
        String auswahl = jComboBoxJahrgang.getSelectedItem().toString();
        int n;
        try {
            n = Integer.parseInt(auswahl);
        } catch (NumberFormatException e) {
            n = 0;
        }

        if (n >= 5 && n <= 10) {
            aktuellerJahrgang = ge.getJahrgang(n);
            aktuellerJahrgang.setKlassenanzahl();

            //System.out.println("Jahrgang: " + aktuellerJahrgang.getJahrgang());
            int klassenanzahl = aktuellerJahrgang.getKlassenanzahl();
            //System.out.println(klassenanzahl);
            jSpinnerAnzahlKlassen.getModel().setValue(klassenanzahl);

            jPanelKlassen.removeAll();
            for (Klasse k : aktuellerJahrgang.getKlassen()) {
                if (k.getKlassengroesse() > 0) {
                    GruppenPanel gp = new GruppenPanel(k.getSchueler(), n + k.getBuchstabe());
                    jPanelKlassen.add(gp);
                }
            }
            
            
            if (n == 5 || n == 6) {
            String anzahlGY = aktuellerJahrgang.getGY() + "";
            //jLabel1Anzahl.setText(anzahlGY);
            jLabel1.setText("ohne Zweig: "+anzahlGY);
            String anzahlGY_MU = aktuellerJahrgang.getGY_MU() + "";
            //jLabel2Anzahl.setText(anzahlGY_MU);
            jLabel2.setText("Musikklassen: "+anzahlGY_MU);
            String anzahlGY_TH = aktuellerJahrgang.getGY_TH() + "";
            //jLabel3Anzahl.setText(anzahlGY_TH);
            jLabel3.setText("Theaterklassen: "+anzahlGY_TH);
        } else if (n == 7) {
            String anzahlGY = aktuellerJahrgang.getGY() + "";

            jLabel1.setText("");
            //jLabel1Anzahl.setText("");
            jLabel2.setText("");
            //jLabel2Anzahl.setText("");
            jLabel3.setText("");
            //jLabel3Anzahl.setText("");
        } else if (n == 8 || n == 9 || n == 10) {
            String anzahlGY_NTG = aktuellerJahrgang.getGY_NTG() + "";
            //jLabel1Anzahl.setText(anzahlGY_NTG);
            jLabel1.setText("NTG-Zweig: "+anzahlGY_NTG);
            String anzahlGY_WSG = aktuellerJahrgang.getGY_WSG() + "";
            //jLabel2Anzahl.setText(anzahlGY_WSG);
            jLabel2.setText("WSG-Zweig: "+anzahlGY_WSG);
            String anzahlGY_SG = aktuellerJahrgang.getGY_SG() + "";
            //jLabel3Anzahl.setText(anzahlGY_SG);
            jLabel3.setText("SG-Zweig: "+anzahlGY_SG);
        }
        String anzahlSchueler = aktuellerJahrgang.getSchuelerAnzahl() + "";
        jLabelSchülergesamt.setText("Gesamt: "+anzahlSchueler);
        //jLabelSchülergesamtAnzahl.setText(anzahlSchueler);
        String anzahlKatholisch = aktuellerJahrgang.getKatholisch() + "";
        jLabelKatholisch.setText("Katholisch: "+anzahlKatholisch);
        //jLabelKatholischAnzahl.setText(anzahlKatholisch);
        String anzahlEthik = aktuellerJahrgang.getEthik() + "";
        jLabelEthik.setText("Ethik: "+anzahlEthik);
        //jLabelEthikAnzahl.setText(anzahlEthik);
        String anzahlEvangelisch = aktuellerJahrgang.getEvangelisch() + "";
        jLabelEvangelisch.setText("Evangelisch:"+anzahlEvangelisch);
        //jLabelEvangelischAnzahl.setText(anzahlEvangelisch);
        String anzahlMännlich = aktuellerJahrgang.getMaennlich() + "";
        jLabelMännlich.setText("Männlich: "+anzahlMännlich);
        //jLabelMännlichAnzahl.setText(anzahlMännlich);
        String anzahlWeiblich = aktuellerJahrgang.getWeiblich() + "";
        jLabelWeiblich.setText("Weiblich: "+anzahlWeiblich);
        //jLabelWeiblichAnzahl.setText(anzahlWeiblich);
        } else {
            jPanelKlassen.removeAll();
            
        }
        jPanelKlassen.revalidate();
        jPanelKlassen.repaint();
       
        
    }

        //Sportgruppen
    //    jPanelSport.removeAll();
    //    for (Klasse s : aktuellerJahrgang.getSportgruppen()) {
    //        if (s.getSportgruppenzahl() > 0) {
    //            jPanelSport.add(new GruppenPanel(s.getSchueler(), n + s.getBuchstabe()));
    //        }
    //    }
    //    jPanelSport.revalidate();
    //    jPanelSport.repaint();
    //Religionsgruppen 
    //    jPanelReligion.removeAll();
    //    for (Klasse r : aktuellerJahrgang.getReligionsgruppen()) {
    //        if (r.getReligionsgruppenzahl() > 0) {
    //            jPanelSport.add(new GruppenPanel(r.getSchueler(), n + r.getBuchstabe()));
    //        }
    //    }
    //    jPanelSport.revalidate();
    //    jPanelSport.repaint();
}
