/**
 *
 * @author heske.timjonathan
 */
package gruppeneinteilung.gui;

import gruppeneinteilung.helper.PrintPDF;
import gruppeneinteilung.helper.Speicherung;
import gruppeneinteilung.model.Gruppeneinteilung;
import gruppeneinteilung.model.Klasse;
import gruppeneinteilung.model.Jahrgang;
import gruppeneinteilung.model.Religionsgruppe;
import gruppeneinteilung.model.Sportgruppe;
import gruppeneinteilung.model.Zweiggruppe;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.GridLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JLabel;
import javax.swing.SpinnerNumberModel;

public class GUI extends javax.swing.JFrame {

    private Gruppeneinteilung ge;
    private Jahrgang aktuellerJahrgang;
    private File file;

    /**
     * Creates new form GUI
     */
    public GUI() {
        
        initComponents();
        ladeDatei();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *///
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxJahrgang = new javax.swing.JComboBox();
        jSpinnerAnzahlKlassen = new javax.swing.JSpinner(new SpinnerNumberModel(4,1,10,1));
        jLabelKlassen = new javax.swing.JLabel();
        jComboBoxSortierung = new javax.swing.JComboBox<String>();
        jButtonJahrgangDrucken = new javax.swing.JButton();
        jLabelSchülergesamt = new javax.swing.JLabel();
        jLabelKatholisch = new javax.swing.JLabel();
        jLabelEthik = new javax.swing.JLabel();
        jLabelEvangelisch = new javax.swing.JLabel();
        jLabelZweig1 = new javax.swing.JLabel();
        jLabelMännlich = new javax.swing.JLabel();
        jLabelWeiblich = new javax.swing.JLabel();
        jLabelZweig2 = new javax.swing.JLabel();
        jLabelZweig3 = new javax.swing.JLabel();
        jCheckBoxReligion = new javax.swing.JCheckBox();
        jCheckBoxSport = new javax.swing.JCheckBox();
        jCheckBoxZweig = new javax.swing.JCheckBox();
        jButtonEinstellungReligion = new javax.swing.JButton();
        jButtonEinstellungSport = new javax.swing.JButton();
        jButtonEinstellungZweig = new javax.swing.JButton();
        jCheckBoxFremdsprachen = new javax.swing.JCheckBox();
        jButtonEinstellungFremdsprachen = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelKlassen = new javax.swing.JPanel();
        jPanelFremdsprachen = new javax.swing.JPanel();
        jPanelReligion = new javax.swing.JPanel();
        jPanelSport = new javax.swing.JPanel();
        jPanelZweig = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemImport = new javax.swing.JMenuItem();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jMenuItemSettings = new javax.swing.JMenuItem();
        jMenuItemPrint = new javax.swing.JMenuItem();
        jMenuItemClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kursmanager");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jComboBoxJahrgang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jahrgang wählen", "5", "6", "7", "8", "9", "10"}));
        jComboBoxJahrgang.setEnabled(false);
        jComboBoxJahrgang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJahrgangActionPerformed(evt);
            }
        });

        jSpinnerAnzahlKlassen.setEnabled(false);
        jSpinnerAnzahlKlassen.setModel(new javax.swing.SpinnerNumberModel(0, 0, 8, 1));
        jSpinnerAnzahlKlassen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerAnzahlKlassenStateChanged(evt);
            }
        });

        jLabelKlassen.setText("Anzahl Klassen:");
        jLabelKlassen.setEnabled(false);

        jComboBoxSortierung.setEnabled(false);
        jComboBoxSortierung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sortierung wählen", "Alphabetisch", "Männlich/Weiblich", "Religion", "Zweig" }));
        jComboBoxSortierung.setName(""); // NOI18N
        jComboBoxSortierung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSortierungActionPerformed(evt);
            }
        });

        jButtonJahrgangDrucken.setText("Jahrgang drucken");
        jButtonJahrgangDrucken.setEnabled(false);
        jButtonJahrgangDrucken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJahrgangDruckenActionPerformed(evt);
            }
        });

        jLabelSchülergesamt.setText("Anzahl Schüler gesamt:");
        jLabelSchülergesamt.setVisible(false);

        jLabelKatholisch.setText("Anzahl Katholisch:");
        jLabelKatholisch.setVisible(false);

        jLabelEthik.setText("Anzahl Ethik:");
        jLabelEthik.setVisible(false);

        jLabelEvangelisch.setText("Anzahl Evangelisch:");
        jLabelEvangelisch.setVisible(false);

        jLabelZweig1.setText("");
        jLabelZweig1.setVisible(false);

        jLabelMännlich.setText("Anzahl Männlich:");
        jLabelMännlich.setVisible(false);

        jLabelWeiblich.setText("Anzahl Weiblich:");
        jLabelWeiblich.setVisible(false);

        jLabelZweig2.setText("");
        jLabelZweig2.setVisible(false);

        jLabelZweig3.setText("");
        jLabelZweig3.setVisible(false);

        jCheckBoxReligion.setText("Religion");
        jCheckBoxReligion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxReligionStateChanged(evt);
            }
        });
        jCheckBoxReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxReligionActionPerformed(evt);
            }
        });
        jCheckBoxReligion.setEnabled(false);

        jCheckBoxSport.setText("Sport");
        jCheckBoxSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxSportActionPerformed(evt);
            }
        });
        jCheckBoxSport.setEnabled(false);

        jCheckBoxZweig.setText("Zweig");
        jCheckBoxZweig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxZweigActionPerformed(evt);
            }
        });
        jCheckBoxZweig.setEnabled(false);

        jButtonEinstellungReligion.setText("Einstellung");
        jButtonEinstellungReligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEinstellungReligionActionPerformed(evt);
            }
        });
        jButtonEinstellungReligion.setEnabled(false);

        jButtonEinstellungSport.setText("Einstellung");
        jButtonEinstellungSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEinstellungSportActionPerformed(evt);
            }
        });
        jButtonEinstellungSport.setEnabled(false);

        jButtonEinstellungZweig.setText("Einstellung");
        jButtonEinstellungZweig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEinstellungZweigActionPerformed(evt);
            }
        });
        jButtonEinstellungZweig.setEnabled(false);

        jCheckBoxFremdsprachen.setEnabled(false);
        jCheckBoxFremdsprachen.setText("Fremdsprachen");
        jCheckBoxFremdsprachen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFremdsprachenActionPerformed(evt);
            }
        });

        jButtonEinstellungFremdsprachen.setEnabled(false);
        jButtonEinstellungFremdsprachen.setText("Einstellungen");
        jButtonEinstellungFremdsprachen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEinstellungFremdsprachenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxSortierung, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxJahrgang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonJahrgangDrucken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelKlassen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerAnzahlKlassen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelSchülergesamt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelKatholisch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEthik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEvangelisch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelZweig1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMännlich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelWeiblich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelZweig2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelZweig3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jCheckBoxFremdsprachen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxReligion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEinstellungReligion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEinstellungFremdsprachen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxSport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEinstellungSport, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jCheckBoxZweig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEinstellungZweig, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxJahrgang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelKlassen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerAnzahlKlassen))
                .addGap(18, 18, 18)
                .addComponent(jComboBoxSortierung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonJahrgangDrucken)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxFremdsprachen)
                    .addComponent(jButtonEinstellungFremdsprachen))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxReligion)
                    .addComponent(jButtonEinstellungReligion))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxSport)
                    .addComponent(jButtonEinstellungSport))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxZweig)
                    .addComponent(jButtonEinstellungZweig))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSchülergesamt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelKatholisch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEthik, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEvangelisch, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMännlich, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWeiblich, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelZweig1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelZweig2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelZweig3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jComboBoxSortierung.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanelKlassen.setLayout(new java.awt.GridLayout(1, 8));
        jTabbedPane1.addTab("Allgemein", jPanelKlassen);

        jPanelFremdsprachen.setLayout(new java.awt.GridLayout(1, 8));
        jTabbedPane1.addTab("Fremdsprachengruppen", jPanelFremdsprachen);

        jPanelReligion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelReligionFocusGained(evt);
            }
        });
        jPanelReligion.setLayout(new java.awt.GridLayout(1, 8));
        jTabbedPane1.addTab("Religionsgruppen", jPanelReligion);

        javax.swing.GroupLayout jPanelSportLayout = new javax.swing.GroupLayout(jPanelSport);
        jPanelSport.setLayout(jPanelSportLayout);
        jPanelSportLayout.setHorizontalGroup(
            jPanelSportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1017, Short.MAX_VALUE)
        );
        jPanelSportLayout.setVerticalGroup(
            jPanelSportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sportgruppen", jPanelSport);

        javax.swing.GroupLayout jPanelZweigLayout = new javax.swing.GroupLayout(jPanelZweig);
        jPanelZweig.setLayout(jPanelZweigLayout);
        jPanelZweigLayout.setHorizontalGroup(
            jPanelZweigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1017, Short.MAX_VALUE)
        );
        jPanelZweigLayout.setVerticalGroup(
            jPanelZweigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Zweiggruppen", jPanelZweig);

        jMenu1.setText("Datei");

        jMenuItemImport.setText("Importieren");
        jMenuItemImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemImportActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemImport);

        jMenuItemOpen.setText("Öffnen");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOpen);

        jMenuItemSave.setText("Speichern");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenuItemSave.setEnabled(false);
        jMenu1.add(jMenuItemSave);

        jMenuItemSaveAs.setText("Speichern unter...");
        jMenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveAsActionPerformed(evt);
            }
        });
        jMenuItemSaveAs.setEnabled(false);
        jMenu1.add(jMenuItemSaveAs);

        jMenuItemSettings.setText("Einstellungen");
        jMenuItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSettingsActionPerformed(evt);
            }
        });
        jMenuItemSettings.setEnabled(false);
        jMenu1.add(jMenuItemSettings);

        jMenuItemPrint.setText("Alles drucken");
        jMenuItemPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrintActionPerformed(evt);
            }
        });
        jMenuItemPrint.setEnabled(false);
        jMenu1.add(jMenuItemPrint);

        jMenuItemClose.setText("Schließen");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bearbeiten");

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("\"\"");

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxJahrgangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJahrgangActionPerformed
        // TODO add your handling code here:
        evalueteJahrgangsAuswahl();
    }//GEN-LAST:event_jComboBoxJahrgangActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        Speicherung sp = new Speicherung();
        ge = sp.serialisierungLaden();
        file = ge.getFile();
        jahrgangAuswahlAktivieren();
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSettingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSettingsActionPerformed

    private void jMenuItemImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemImportActionPerformed
        // TODO add your handling code here:
        ge = new Gruppeneinteilung();
        ge.asvImport();
        jahrgangAuswahlAktivieren();
    }//GEN-LAST:event_jMenuItemImportActionPerformed

    private void jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseActionPerformed
        // TODO add your handling code here:
        merkeGeladeneDatei();
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItemCloseActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        // TODO add your handling code here:
        new Speicherung(ge).speichern();
        file = ge.getFile();
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jComboBoxSortierungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSortierungActionPerformed
        // TODO add your handling code here:
        String sortierung = jComboBoxSortierung.getSelectedItem().toString();
        for (Klasse k : aktuellerJahrgang.getKlassen()) {
            switch (sortierung) {
                case "Alphabetisch":
                    k.sortierenName();
                    break;
                case "Männlich/Weiblich":
                    k.sortierenGeschlecht();
                    break;
                case "Religion":
                    k.sortierenReligion();
                    break;
                case "Zweig":
                    k.sortierenZweig();
                    break;
            }
        }
        Component[] comps = jPanelKlassen.getComponents();
        for (Component comp : comps) {
            KlassenPanel gp = (KlassenPanel) comp;
            gp.aktualisiereListModel();
            gp.revalidate();
            gp.repaint();
        }
        jPanelKlassen.revalidate();
        jPanelKlassen.repaint();
    }//GEN-LAST:event_jComboBoxSortierungActionPerformed

    private void jMenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsActionPerformed
        // TODO add your handling code here:
        new Speicherung(ge).speichernUnter();
        this.setTitle("Kursmanager - " + ge.getFile().toString());
        file = ge.getFile();
    }//GEN-LAST:event_jMenuItemSaveAsActionPerformed

    private void jMenuItemPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrintActionPerformed
        // TODO add your handling code here:
        PrintPDF printPdf = new PrintPDF(ge);
        printPdf.Drucken("Alle Klassen");
    }//GEN-LAST:event_jMenuItemPrintActionPerformed

    private void jButtonJahrgangDruckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJahrgangDruckenActionPerformed
        // TODO add your handling code here:
        PrintPDF printPdf = new PrintPDF(ge);
        int n = Integer.parseInt(jComboBoxJahrgang.getSelectedItem().toString());
        Jahrgang j = ge.getJahrgang(n);
        String z = Integer.toString(n);
        printPdf.druckeJahrgang(j, "Jahrgang" + z);
    }//GEN-LAST:event_jButtonJahrgangDruckenActionPerformed

    private void jCheckBoxReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxReligionActionPerformed
        // TODO add your handling code here:
        if(jCheckBoxReligion.isSelected()){
            aktuellerJahrgang.setNachReligion(true);
             new EinstellungFrame(aktuellerJahrgang, this).setVisible(true);
             jButtonEinstellungReligion.setEnabled(true);
        } else {
            aktuellerJahrgang.setNachReligion(false);
            aktuellerJahrgang.clearReligionsgruppen();
            jButtonEinstellungReligion.setEnabled(false);
            jPanelReligion.removeAll();
            jPanelReligion.revalidate();
            jPanelReligion.repaint();
            
        }
        

    }//GEN-LAST:event_jCheckBoxReligionActionPerformed

    private void jButtonEinstellungReligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEinstellungReligionActionPerformed
        // TODO add your handling code here:
        new EinstellungFrame(aktuellerJahrgang, this).setVisible(true);
    }//GEN-LAST:event_jButtonEinstellungReligionActionPerformed

    private void jCheckBoxSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxSportActionPerformed
        // TODO add your handling code here:
        new EinstellungFrame(aktuellerJahrgang, this).setVisible(true);

    }//GEN-LAST:event_jCheckBoxSportActionPerformed

    private void jCheckBoxZweigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxZweigActionPerformed
        // TODO add your handling code here:
        new EinstellungFrame(aktuellerJahrgang, this).setVisible(true);

    }//GEN-LAST:event_jCheckBoxZweigActionPerformed

    private void jButtonEinstellungSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEinstellungSportActionPerformed
        // TODO add your handling code here:
        new EinstellungFrame(aktuellerJahrgang, this).setVisible(true);
    }//GEN-LAST:event_jButtonEinstellungSportActionPerformed

    private void jButtonEinstellungZweigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEinstellungZweigActionPerformed
        // TODO add your handling code here:
        new EinstellungFrame(aktuellerJahrgang, this).setVisible(true);
    }//GEN-LAST:event_jButtonEinstellungZweigActionPerformed

    private void jSpinnerAnzahlKlassenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerAnzahlKlassenStateChanged
        // TODO add your handling code here:


    }//GEN-LAST:event_jSpinnerAnzahlKlassenStateChanged

    private void jCheckBoxFremdsprachenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFremdsprachenActionPerformed
        // TODO add your handling code here:
        new EinstellungFrame(aktuellerJahrgang, this).setVisible(true);
    }//GEN-LAST:event_jCheckBoxFremdsprachenActionPerformed

    private void jButtonEinstellungFremdsprachenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEinstellungFremdsprachenActionPerformed
        // TODO add your handling code here:
        new EinstellungFrame(aktuellerJahrgang, this).setVisible(true);
    }//GEN-LAST:event_jButtonEinstellungFremdsprachenActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jPanelReligionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelReligionFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanelReligionFocusGained

    private void jCheckBoxReligionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxReligionStateChanged

    }//GEN-LAST:event_jCheckBoxReligionStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        merkeGeladeneDatei();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEinstellungFremdsprachen;
    private javax.swing.JButton jButtonEinstellungReligion;
    private javax.swing.JButton jButtonEinstellungSport;
    private javax.swing.JButton jButtonEinstellungZweig;
    private javax.swing.JButton jButtonJahrgangDrucken;
    private javax.swing.JCheckBox jCheckBoxFremdsprachen;
    private javax.swing.JCheckBox jCheckBoxReligion;
    private javax.swing.JCheckBox jCheckBoxSport;
    private javax.swing.JCheckBox jCheckBoxZweig;
    private javax.swing.JComboBox jComboBoxJahrgang;
    private javax.swing.JComboBox<String> jComboBoxSortierung;
    private javax.swing.JLabel jLabelEthik;
    private javax.swing.JLabel jLabelEvangelisch;
    private javax.swing.JLabel jLabelKatholisch;
    private javax.swing.JLabel jLabelKlassen;
    private javax.swing.JLabel jLabelMännlich;
    private javax.swing.JLabel jLabelSchülergesamt;
    private javax.swing.JLabel jLabelWeiblich;
    private javax.swing.JLabel jLabelZweig1;
    private javax.swing.JLabel jLabelZweig2;
    private javax.swing.JLabel jLabelZweig3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemImport;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemPrint;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JMenuItem jMenuItemSettings;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFremdsprachen;
    private javax.swing.JPanel jPanelKlassen;
    private javax.swing.JPanel jPanelReligion;
    private javax.swing.JPanel jPanelSport;
    private javax.swing.JPanel jPanelZweig;
    private javax.swing.JSpinner jSpinnerAnzahlKlassen;
    private javax.swing.SpinnerModel modelKlassenAnzahl = new javax.swing.SpinnerNumberModel(0, 0, 10, 1);
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    public void jahrgangAuswahlAktivieren() {
        jMenuItemSave.setEnabled(true);
        jMenuItemSaveAs.setEnabled(true);
        jMenuItemPrint.setEnabled(true);
        jComboBoxJahrgang.setEnabled(true);
        String dateiname;
        if (ge.getFile() == null) {
            dateiname = "";
        } else {
            dateiname = " - " + ge.getFile().toString();
        }
        this.setTitle("Kursmanager" + dateiname);
        if (ge.getAktJahrgang() != null) {
            System.out.println("Aktueller Jahrgang gefunden: " + ge.getAktJahrgang().getJahrgang());
            aktuellerJahrgang = ge.getAktJahrgang();
            jComboBoxJahrgang.setSelectedIndex(aktuellerJahrgang.getJahrgang() - 4);
        }
    }

    public void aktiviereJahrgangComponents(boolean istAn) {
        jButtonJahrgangDrucken.setEnabled(istAn);
        jSpinnerAnzahlKlassen.setEnabled(istAn);
        jComboBoxSortierung.setEnabled(istAn);
        jCheckBoxReligion.setEnabled(istAn);
        jCheckBoxSport.setEnabled(istAn);
        jCheckBoxZweig.setEnabled(istAn);
        jCheckBoxFremdsprachen.setEnabled(istAn);
        jLabelKlassen.setEnabled(istAn);
        jLabelSchülergesamt.setVisible(istAn);
        jLabelKatholisch.setVisible(istAn);
        jLabelEvangelisch.setVisible(istAn);
        jLabelEthik.setVisible(istAn);
        jLabelMännlich.setVisible(istAn);
        jLabelWeiblich.setVisible(istAn);
        jLabelZweig1.setVisible(istAn);
        jLabelZweig2.setVisible(istAn);
        jLabelZweig3.setVisible(istAn);
    }

    public void evalueteJahrgangsAuswahl() {
        String auswahl = jComboBoxJahrgang.getSelectedItem().toString();
        int n;
        try {
            n = Integer.parseInt(auswahl);
        } catch (NumberFormatException e) {
            // Kein Jahrgang ausgewählt -> aufräumen
            jSpinnerAnzahlKlassen.getModel().setValue(0);
            aktiviereJahrgangComponents(false);
            jPanelKlassen.removeAll();
            jPanelKlassen.revalidate();
            jPanelKlassen.repaint();
            return;
        }

        aktuellerJahrgang = ge.getJahrgang(n);
        ge.setAktJahrgang(aktuellerJahrgang);
        aktuellerJahrgang.setKlassenanzahl();
        int klassenanzahl = aktuellerJahrgang.getKlassenanzahl();
        jSpinnerAnzahlKlassen.getModel().setValue(klassenanzahl);

        aktiviereJahrgangComponents(true);
        klassenAnzeigen();
        aktualisiereLabelJahrgang();
        
        if(aktuellerJahrgang.istNachReligion()){
            jCheckBoxReligion.setSelected(true);
            jButtonEinstellungReligion.setEnabled(true);
            religionsgruppenAnzeigen();
        }



        jPanelKlassen.revalidate();
        jPanelKlassen.repaint();

    }
    public void aktualisiereLabelJahrgang(){
        int n = aktuellerJahrgang.getJahrgang();
                if (n == 5 || n == 6) {
            String anzahlGY = aktuellerJahrgang.getGY() + "";
            //jLabel1Anzahl.setText(anzahlGY);
            jLabelZweig1.setText("ohne Zweig: " + anzahlGY);
            String anzahlGY_MU = aktuellerJahrgang.getGY_MU() + "";
            //jLabel2Anzahl.setText(anzahlGY_MU);
            jLabelZweig2.setText("Musikklassen: " + anzahlGY_MU);
            String anzahlGY_TH = aktuellerJahrgang.getGY_TH() + "";
            //jLabel3Anzahl.setText(anzahlGY_TH);
            jLabelZweig3.setText("Theaterklassen: " + anzahlGY_TH);
        } else if (n == 7) {
            String anzahlGY = aktuellerJahrgang.getGY() + "";

            jLabelZweig1.setText("");
            //jLabel1Anzahl.setText("");
            jLabelZweig2.setText("");
            //jLabel2Anzahl.setText("");
            jLabelZweig3.setText("");
            //jLabel3Anzahl.setText("");
        } else if (n == 8 || n == 9 || n == 10) {
            String anzahlGY_NTG = aktuellerJahrgang.getGY_NTG() + "";
            //jLabel1Anzahl.setText(anzahlGY_NTG);
            jLabelZweig1.setText("NTG-Zweig: " + anzahlGY_NTG);
            String anzahlGY_WSG = aktuellerJahrgang.getGY_WSG() + "";
            //jLabel2Anzahl.setText(anzahlGY_WSG);
            jLabelZweig2.setText("WSG-Zweig: " + anzahlGY_WSG);
            String anzahlGY_SG = aktuellerJahrgang.getGY_SG() + "";
            //jLabel3Anzahl.setText(anzahlGY_SG);
            jLabelZweig3.setText("SG-Zweig: " + anzahlGY_SG);
        }

        String anzahlSchueler = aktuellerJahrgang.getSchuelerAnzahl() + "";
        jLabelSchülergesamt.setText("Gesamt: " + anzahlSchueler);
        //jLabelSchülergesamtAnzahl.setText(anzahlSchueler);
        String anzahlKatholisch = aktuellerJahrgang.getKatholisch() + "";
        jLabelKatholisch.setText("Katholisch: " + anzahlKatholisch);
        //jLabelKatholischAnzahl.setText(anzahlKatholisch);
        String anzahlEthik = aktuellerJahrgang.getEthik() + "";
        jLabelEthik.setText("Ethik: " + anzahlEthik);
        //jLabelEthikAnzahl.setText(anzahlEthik);
        String anzahlEvangelisch = aktuellerJahrgang.getEvangelisch() + "";
        jLabelEvangelisch.setText("Evangelisch:" + anzahlEvangelisch);
        //jLabelEvangelischAnzahl.setText(anzahlEvangelisch);
        String anzahlMännlich = aktuellerJahrgang.getMaennlich() + "";
        jLabelMännlich.setText("Männlich: " + anzahlMännlich);
        //jLabelMännlichAnzahl.setText(anzahlMännlich);
        String anzahlWeiblich = aktuellerJahrgang.getWeiblich() + "";
        jLabelWeiblich.setText("Weiblich: " + anzahlWeiblich);
        //jLabelWeiblichAnzahl.setText(anzahlWeiblich);
    }

    public void klassenAnzeigen() {
        jPanelKlassen.removeAll();
        for (Klasse k : aktuellerJahrgang.getKlassen()) {
            if (k.getKlassengroesse() > 0) {
                KlassenPanel gp = new KlassenPanel(k.getSchueler(), aktuellerJahrgang.getJahrgang() + k.getBuchstabe());
                jPanelKlassen.add(gp);
            }
        }
    }

    public void sportgruppenAnzeigen() {
        jPanelSport.removeAll();
        for (Sportgruppe s : aktuellerJahrgang.getSportgruppen()) {
            if (s.getSportgroesse() > 0) {
                jPanelSport.add(new GruppenPanel(s.getSchueler(), "" + s.getSportgroesse()));
            }
        }
        jPanelSport.revalidate();
        jPanelSport.repaint();
    }

    public void religionsgruppenAnzeigen() {

        jPanelReligion.removeAll();
        for (Religionsgruppe r : aktuellerJahrgang.getReligionsgruppen()) {
            
                jPanelReligion.add(new GruppenPanel(r.getSchueler(), ""+r.getReligion()+": " + r.getReligiongroesse()+" Schüler"));
     
        }
        jPanelReligion.revalidate();
        jPanelReligion.repaint();
    }

    public void zweiggruppenAnzeigen() {
        jPanelZweig.removeAll();
        for (Zweiggruppe r : aktuellerJahrgang.getZweiggruppen()) {

                jPanelZweig.add(new GruppenPanel(r.getSchueler(), "" + r.getZahl()));

        }
        jPanelZweig.revalidate();
        jPanelZweig.repaint();
    }

    public void fremdsprachengruppenAnzeigen() {
        //   jPanelFremdsprachen.removeAll();
        //   for (Fremdsprachengruppen f : aktuellerJahrgang.gibFremdsprachengruppen()) {
        //       if (f.getZahl() > 0) {
        //           jPanelFremdsprachen.add(new GruppenPanel(f.getSchueler(), ""+f.getZahl()));
        //       }
        //   }
        //   jPanelFremdsprachen.revalidate();
        //   jPanelFremdsprachen.repaint();
    }

    public void merkeGeladeneDatei() {
        try {
            FileWriter fw = new FileWriter("ge.ini");
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(file.getAbsolutePath());
            System.out.println(file.getAbsolutePath());
            bw.close();
        } catch (IOException ex) {

        }
    }

    public void ladeDatei() {
        try {
            File ini = new File("ge.ini");
            if(ini.exists()){
            FileReader fr = new FileReader(ini);
            BufferedReader br = new BufferedReader(fr);

            String dateiname = br.readLine();
            Speicherung sp = new Speicherung(dateiname);
            ge = sp.serialisierungLaden();
            file = ge.getFile();
            jahrgangAuswahlAktivieren();
            
            br.close();
            }
        } catch (IOException ex) {

        }
    }

}
